export const START_FETCHING = 'START_FETCHING';
export const GET_DATA_PRODUCTS = 'GET_DATA_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ONE_FROM_CART = 'REMOVE_ONE_FROM_CART';
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
